### ISSUE TITLE
map label style

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#102]
UX/UI for map on-hover labels

**Comment by elbfox** [comment]
Is the map in step 2 something we can replicate for step 4 in the no-MOGA version with dot colors coordinated to the top decision alternative at each dam? Like if we brought in the map recommendation tab (which I had removed entirely) and instead of a static map pulled from a folder had the dots for each dam site coordinate to the colors in those multi-dam maps, where green = keep maintain, black = remove, yellow = improve fish passage, red = improve both fish passage and hydro, and blue = improve hydro?
