### ISSUE TITLE
Multi Dam Tables

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#135]
mentioned in #124 for downloadable tables,

which tables are to be displayed on the Combined Results Page

**Comment by elbfox** [comment]
No multi-dam tables for viewing on-screen, because that would be really hard to interpret. For download, we can let the user download a version of Decisions (which is 2D) that is ranked according to their inputs. If it's easy to present only the top 5-10 scenarios, then that would be better, but otherwise it's fine. I will add a pdf link with some descriptive text explaining what the file includes.

**Comment by sythel** [comment]
Decisions Downloadable as 8x995 csv file 

for top 5-10 scenarios I assume I would need [idxRank from WSM.R](https://github.com/dams-mcda/Dams-MCDA/blob/8c824f7e67ecd6d90369f3077e7d01fe8c557a61/src/dams_mcda/WSM.R#L360)?

**Comment by elbfox** [comment]
Yes, idxRank will order it, and then we could just cut everything except the top 5 - 10.

**Comment by sythel** [comment]
set to 10 rows for now

I think I discovered a bug: returned map is using the score instead of the idxScen which I beleive is the index for the map it should be using

**Comment by sythel** [comment]
tasks complete, closing
